version: '2'
services:
    indepth2-mysql:
        container_name: indepth2-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/InDepth2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=indepth2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1
